"""Main training pipeline for the neuro-fuzzy stress detection project."""

from __future__ import annotations

import argparse
import json
import logging
import re
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Dict, Sequence

import numpy as np
import pandas as pd

from src.configs.config import SystemConfig, export_default_config, load_system_config
from src.data.load_data import StressDatasetGenerator
from src.evaluation.accuracy import accuracy_analysis
from src.evaluation.confusion_matrix import confusion_matrix_report
from src.evaluation.precision import precision_analysis
from src.evaluation.recall import recall_analysis
from src.fuzzy_logic.inference import FuzzyInferenceEngine
from src.fuzzy_logic.membership_functions import build_membership_function
from src.fuzzy_logic.rules import FuzzyRuleBase, LinguisticVariable
from src.models.save_load import ModelPersistenceManager
from src.neural_network.network import NeuralNetwork, TrainingHistory
from src.neuro_fuzzy.neuro_fuzzy_system import NeuroFuzzySystem
from src.preprocessing.preprocess import DataPreprocessor
from src.utils.experiment_tracker import ExperimentTracker
from src.utils.logging_utils import LoggerConfig, LoggerManager
from src.utils.validation_utils import DataValidator
from src.visualization.plots import PlotManager


LOGGER = logging.getLogger(__name__)
DATA_PATH = "artifacts/stress_dataset.csv"


@dataclass
class PipelineArtifacts:
    """Structured output paths generated by the pipeline."""

    dataset_path: str
    neural_model_path: str
    neuro_fuzzy_model_path: str
    neural_metadata_path: str
    neuro_fuzzy_metadata_path: str
    experiment_record_path: str
    metrics_path: str
    config_snapshot_path: str
    plot_paths: Dict[str, str]


def setup_logging(config: SystemConfig) -> logging.Logger:
    """Configure application logging from the system config."""

    logging_config = config.get_logging_config()
    level = getattr(logging, logging_config.level.upper(), logging.INFO)
    manager = LoggerManager(
        LoggerConfig(
            logger_name=logging_config.logger_name,
            level=level,
            log_file=logging_config.log_file,
            console_enabled=logging_config.log_to_console,
            file_enabled=logging_config.log_to_file,
            structured_logs=logging_config.enable_json_logging,
            propagate=logging_config.propagate,
            max_bytes=logging_config.max_file_size_mb * 1024 * 1024,
            backup_count=logging_config.backup_count,
            timestamp_format=logging_config.date_format,
            message_format=logging_config.log_format,
        )
    )
    application_logger = manager.get_logger()

    root_logger = logging.getLogger()
    root_logger.handlers.clear()
    root_logger.setLevel(level)
    for handler in application_logger.handlers:
        root_logger.addHandler(handler)

    return application_logger


def generate_dataset(config: SystemConfig) -> tuple[pd.DataFrame, Path]:
    """Generate and optionally persist the synthetic dataset."""

    dataset_config = config.get_dataset_config()
    generator = StressDatasetGenerator(
        num_samples=dataset_config.num_samples,
        random_state=dataset_config.random_seed,
    )
    dataset = generator.generate_dataset()
    validation_summary = generator.validate_distribution(dataset)
    LOGGER.info("Dataset validation summary: %s", validation_summary)

    dataset_path = dataset_config.get_dataset_path()
    if dataset_config.persist_generated_data:
        dataset_path = generator.save_dataset(dataset, dataset_path)

    return dataset, Path(dataset_path)


def ensure_dataset_exists(data_path: Path, config: SystemConfig) -> pd.DataFrame:
    """Load a dataset from disk or generate one when missing."""

    if data_path.exists():
        return pd.read_csv(data_path)

    dataset, _ = generate_dataset(config)
    data_path.parent.mkdir(parents=True, exist_ok=True)
    dataset.to_csv(data_path, index=False)
    return dataset


def build_preprocessor(config: SystemConfig) -> DataPreprocessor:
    """Create the preprocessing pipeline from configuration."""

    dataset_config = config.get_dataset_config()
    test_size = 1.0 - dataset_config.train_split_ratio - dataset_config.validation_split_ratio
    missing_strategy_map = {
        "raise": "median",
        "drop": "median",
        "mean_impute": "mean",
        "median_impute": "median",
    }

    return DataPreprocessor(
        missing_strategy=missing_strategy_map.get(dataset_config.missing_value_strategy, "median"),
        outlier_method="zscore",
        outlier_threshold=dataset_config.outlier_zscore_threshold,
        scaling_method="standard",
        normalization_method=None,
        variance_threshold=0.0,
        test_size=test_size,
        validation_size=dataset_config.validation_split_ratio,
        random_state=dataset_config.random_seed,
        stratify=True,
    )


def build_neural_network(config: SystemConfig, input_size: int) -> NeuralNetwork:
    """Create the neural-network model."""

    model_config = config.get_model_config()
    training_config = config.get_training_config()

    optimizer_map = {
        "sgd": "gd",
        "momentum": "momentum",
        "adam": "adam",
        "rmsprop": "adam",
    }
    weight_init_map = {
        "he_normal": "he",
        "he_uniform": "he",
        "xavier": "xavier",
        "xavier_uniform": "xavier_uniform",
        "normal": "normal",
    }

    return NeuralNetwork(
        input_size=input_size,
        hidden_layers=model_config.hidden_layers,
        output_size=model_config.output_size,
        activation=model_config.activation_hidden,
        output_activation=model_config.activation_output,
        weight_init=weight_init_map.get(model_config.weight_init, "he"),
        optimizer=optimizer_map.get(training_config.optimizer, "adam"),
        learning_rate=training_config.learning_rate,
        batch_size=training_config.batch_size,
        epochs=training_config.epochs,
        l2_lambda=training_config.l2_regularization,
        dropout_rate=training_config.dropout_rate,
        early_stopping=training_config.early_stopping,
        patience=training_config.early_stopping_patience,
        min_learning_rate=training_config.min_learning_rate,
        shuffle=training_config.shuffle_each_epoch,
        random_state=training_config.random_seed,
    )


def create_membership_function(
    function_type: str,
    lower: float,
    center: float,
    upper: float,
) -> Any:
    """Create a low/medium/high-ready membership function."""

    function_type = function_type.strip().lower()
    spread = max((upper - lower) / 4.0, 1e-3)

    if function_type == "gaussian":
        return (
            build_membership_function("gaussian", mean=lower, sigma=spread),
            build_membership_function("gaussian", mean=center, sigma=spread),
            build_membership_function("gaussian", mean=upper, sigma=spread),
        )
    if function_type in {"triangular", "trapezoidal", "gbell"}:
        if function_type == "triangular":
            return (
                build_membership_function("triangular", a=lower - spread, b=lower, c=center),
                build_membership_function("triangular", a=lower, b=center, c=upper),
                build_membership_function("triangular", a=center, b=upper, c=upper + spread),
            )
        if function_type == "trapezoidal":
            return (
                build_membership_function(
                    "trapezoidal",
                    a=lower - spread,
                    b=lower - spread / 2.0,
                    c=lower,
                    d=center,
                ),
                build_membership_function(
                    "trapezoidal",
                    a=lower,
                    b=center - spread / 2.0,
                    c=center + spread / 2.0,
                    d=upper,
                ),
                build_membership_function(
                    "trapezoidal",
                    a=center,
                    b=upper,
                    c=upper + spread / 2.0,
                    d=upper + spread,
                ),
            )
        return (
            build_membership_function("gbell", a=spread, b=2.0, c=lower),
            build_membership_function("gbell", a=spread, b=2.0, c=center),
            build_membership_function("gbell", a=spread, b=2.0, c=upper),
        )

    raise ValueError(f"Unsupported membership function type: {function_type}")


def build_fuzzy_rule_base(
    feature_frame: pd.DataFrame,
    class_labels: Sequence[str],
    config: SystemConfig,
) -> FuzzyRuleBase:
    """Create a fuzzy rule base aligned with the selected features."""

    fuzzy_config = config.get_fuzzy_config()
    rule_base = FuzzyRuleBase(
        conjunction_operator=fuzzy_config.conjunction_operator,
        disjunction_operator=fuzzy_config.disjunction_operator,
        conflict_resolution="max_activation",
    )

    for column in feature_frame.columns:
        series = feature_frame[column].astype(float)
        low = float(series.quantile(0.2))
        center = float(series.quantile(0.5))
        high = float(series.quantile(0.8))

        variable = LinguisticVariable(name=column)
        low_mf, medium_mf, high_mf = create_membership_function(
            fuzzy_config.membership_function_type,
            low,
            center,
            high,
        )
        variable.add_term("low", low_mf)
        variable.add_term("medium", medium_mf)
        variable.add_term("high", high_mf)
        rule_base.add_linguistic_variable(variable)

    output_variable = LinguisticVariable(name="stress_level")
    low_mf, medium_mf, high_mf = create_membership_function(
        fuzzy_config.membership_function_type,
        fuzzy_config.low_range[1],
        float(np.mean(fuzzy_config.medium_range)),
        fuzzy_config.high_range[0],
    )
    output_variable.add_term("low", low_mf)
    output_variable.add_term("medium", medium_mf)
    output_variable.add_term("high", high_mf)
    rule_base.add_linguistic_variable(output_variable)

    available = set(feature_frame.columns)
    rule_definitions = [
        ("rule_1", "IF sleep_hours IS low AND mental_fatigue_score IS high THEN stress_level IS high"),
        ("rule_2", "IF work_hours IS high AND work_pressure_score IS high THEN stress_level IS high"),
        ("rule_3", "IF heart_rate IS high AND mental_fatigue_score IS high THEN stress_level IS high"),
        ("rule_4", "IF screen_time IS high AND caffeine_intake IS high THEN stress_level IS medium"),
        ("rule_5", "IF physical_activity_hours IS high AND social_interaction_hours IS high THEN stress_level IS low"),
        ("rule_6", "IF sleep_hours IS high AND work_pressure_score IS low THEN stress_level IS low"),
        ("rule_7", "IF sleep_hours IS medium AND work_pressure_score IS medium THEN stress_level IS medium"),
        ("rule_8", "IF physical_activity_hours IS low AND work_pressure_score IS high THEN stress_level IS high"),
        ("rule_9", "IF social_interaction_hours IS low AND mental_fatigue_score IS high THEN stress_level IS high"),
        ("rule_10", "IF sleep_hours IS high AND physical_activity_hours IS high THEN stress_level IS low"),
    ]

    for rule_id, expression in rule_definitions:
        referenced_features = extract_rule_variables(expression)
        if referenced_features.issubset(available):
            rule_base.add_rule(rule_id, expression, weight=fuzzy_config.rule_weight_default)

    if not rule_base.rules:
        fallback_feature = feature_frame.columns[0]
        rule_base.add_rule(
            "rule_fallback_low",
            f"IF {fallback_feature} IS low THEN stress_level IS low",
            weight=fuzzy_config.rule_weight_default,
        )
        rule_base.add_rule(
            "rule_fallback_high",
            f"IF {fallback_feature} IS high THEN stress_level IS high",
            weight=fuzzy_config.rule_weight_default,
        )

    normalized_labels = {label.strip().lower() for label in class_labels}
    if normalized_labels != {"low", "medium", "high"}:
        LOGGER.warning("Fuzzy rule base assumes class labels Low/Medium/High. Found %s", list(class_labels))

    return rule_base


def extract_rule_variables(rule_expression: str) -> set[str]:
    """Extract antecedent variable names from a fuzzy rule expression."""

    return {
        match.group(1).strip().lower()
        for match in re.finditer(r"([A-Za-z_][A-Za-z0-9_]*)\s+IS\s+[A-Za-z_][A-Za-z0-9_]*", rule_expression)
        if match.group(1).strip().lower() != "stress_level"
    }


def build_neuro_fuzzy_system(
    neural_network: NeuralNetwork,
    feature_frame: pd.DataFrame,
    config: SystemConfig,
) -> NeuroFuzzySystem:
    """Create the hybrid neuro-fuzzy system."""

    fuzzy_config = config.get_fuzzy_config()
    model_config = config.get_model_config()
    rule_base = build_fuzzy_rule_base(feature_frame, model_config.class_labels, config)
    output_universe = np.linspace(
        fuzzy_config.output_universe_range[0],
        fuzzy_config.output_universe_range[1],
        fuzzy_config.input_universe_resolution,
    )
    inference_engine = FuzzyInferenceEngine(
        rule_base=rule_base,
        output_universes={"stress_level": output_universe},
        default_resolution=fuzzy_config.input_universe_resolution,
    )
    return NeuroFuzzySystem(
        neural_network=neural_network,
        fuzzy_inference_engine=inference_engine,
        feature_names=feature_frame.columns.tolist(),
        class_labels=model_config.class_labels,
        neural_weight=model_config.neural_weight,
        fuzzy_weight=model_config.fuzzy_weight,
    )


def predict_fuzzy_only(
    inference_engine: FuzzyInferenceEngine,
    feature_frame: pd.DataFrame,
    class_labels: Sequence[str],
) -> np.ndarray:
    """Generate fuzzy-only class predictions."""

    class_to_index = {label.strip().lower(): index for index, label in enumerate(class_labels)}
    predictions: list[int] = []

    for _, row in feature_frame.iterrows():
        result = inference_engine.infer({column: float(row[column]) for column in feature_frame.columns})
        probabilities = np.zeros(len(class_labels), dtype=float)
        term_strengths = result.aggregated_outputs.get("stress_level", {})

        for term_name, strength in term_strengths.items():
            label_index = class_to_index.get(term_name.strip().lower())
            if label_index is not None:
                probabilities[label_index] = max(probabilities[label_index], float(strength))

        if probabilities.sum() == 0.0:
            probabilities[:] = 1.0 / len(class_labels)
        else:
            probabilities = probabilities / probabilities.sum()

        predictions.append(int(np.argmax(probabilities)))

    return np.asarray(predictions, dtype=int)


def run_basic_pipeline(data_path: Path) -> None:
    """Run the user's requested step-by-step training flow."""

    config = load_system_config()
    setup_logging(config)

    print("\nSTEP 1 — Loading Dataset")
    df = ensure_dataset_exists(data_path, config)
    print(df.head())

    print("\nSTEP 2 — Preprocessing")
    processor = build_preprocessor(config)
    split_data = processor.split_data(df)

    X_train = split_data.X_train
    X_test = split_data.X_test
    y_train = split_data.y_train.to_numpy()
    y_test = split_data.y_test.to_numpy()

    print("Train shape:", X_train.shape)
    print("Test shape:", X_test.shape)

    print("\nSTEP 3 — Training Neural Network")
    nn = NeuralNetwork(
        input_size=X_train.shape[1],
        hidden_layers=[16, 12],
        output_size=3,
        learning_rate=0.01,
        epochs=150,
        optimizer="adam",
    )
    nn.fit(X_train.to_numpy(), y_train, verbose=False)

    print("\nSTEP 4 — Fuzzy Inference")
    basic_config = SystemConfig()
    rule_base = build_fuzzy_rule_base(X_train, basic_config.model.class_labels, basic_config)
    output_universe = np.linspace(
        basic_config.fuzzy.output_universe_range[0],
        basic_config.fuzzy.output_universe_range[1],
        basic_config.fuzzy.input_universe_resolution,
    )
    fuzzy_system = FuzzyInferenceEngine(
        rule_base=rule_base,
        output_universes={"stress_level": output_universe},
        default_resolution=basic_config.fuzzy.input_universe_resolution,
    )
    fuzzy_predictions = predict_fuzzy_only(
        fuzzy_system,
        X_test,
        basic_config.model.class_labels,
    )
    _ = fuzzy_predictions

    print("\nSTEP 5 — Neuro Fuzzy Combination")
    hybrid_model = NeuroFuzzySystem(
        neural_network=nn,
        fuzzy_inference_engine=fuzzy_system,
        feature_names=X_train.columns.tolist(),
        class_labels=basic_config.model.class_labels,
    )
    hybrid_predictions = hybrid_model.predict(X_test)

    print("\nSTEP 6 — Evaluation")
    accuracy = accuracy_analysis(y_test, hybrid_predictions)["accuracy"]
    precision = precision_analysis(y_test, hybrid_predictions)["precision"]
    recall = recall_analysis(y_test, hybrid_predictions)["recall"]
    report = {
        "accuracy": accuracy_analysis(y_test, hybrid_predictions),
        "precision": precision_analysis(y_test, hybrid_predictions),
        "recall": recall_analysis(y_test, hybrid_predictions),
        "confusion_matrix": confusion_matrix_report(
            y_test,
            hybrid_predictions,
            labels=list(range(len(basic_config.model.class_labels))),
        ),
    }

    print("\nAccuracy:", accuracy)
    print("\nPrecision:", precision)
    print("\nRecall:", recall)
    print("\nDetailed Report")
    print(json.dumps(report, indent=4, default=_json_default))

    print("\nSTEP 7 — Visualization")
    plot_manager = PlotManager()
    plot_manager.plot_confusion_matrix_heatmap(
        report["confusion_matrix"]["matrix"],
        labels=basic_config.model.class_labels,
        title="Hybrid Model Confusion Matrix",
        save_path=data_path.parent / "basic_pipeline_confusion_matrix.png",
        show=False,
    )

    print("\nPIPELINE COMPLETE")


def compute_f1_macro(y_true: Sequence[int], y_pred: Sequence[int]) -> float:
    """Compute macro-averaged F1 score from precision and recall."""

    precision = precision_analysis(y_true, y_pred)["precision"]
    recall = recall_analysis(y_true, y_pred)["recall"]
    if precision + recall == 0.0:
        return 0.0
    return float(2.0 * precision * recall / (precision + recall))


def evaluate_predictions(
    y_true: Sequence[int],
    y_pred: Sequence[int],
    class_labels: Sequence[str],
) -> Dict[str, Any]:
    """Compute evaluation metrics and confusion-matrix details."""

    metrics = {
        "accuracy": accuracy_analysis(y_true, y_pred),
        "precision": precision_analysis(y_true, y_pred, average="macro"),
        "recall": recall_analysis(y_true, y_pred, average="macro"),
        "f1_macro": compute_f1_macro(y_true, y_pred),
        "confusion_matrix": confusion_matrix_report(
            y_true,
            y_pred,
            labels=list(range(len(class_labels))),
        ),
    }
    return metrics


def summarize_metrics(metric_bundle: Dict[str, Any]) -> Dict[str, float]:
    """Flatten the most important metrics for tracking."""

    return {
        "accuracy": float(metric_bundle["accuracy"]["accuracy"]),
        "precision_macro": float(metric_bundle["precision"]["precision"]),
        "recall_macro": float(metric_bundle["recall"]["recall"]),
        "f1_macro": float(metric_bundle["f1_macro"]),
    }


def generate_plots(
    dataset: pd.DataFrame,
    training_history: TrainingHistory,
    neural_metrics: Dict[str, Any],
    neuro_fuzzy_metrics: Dict[str, Any],
    class_labels: Sequence[str],
    output_directory: Path,
    show_plots: bool,
) -> Dict[str, str]:
    """Generate training and evaluation plots."""

    plot_manager = PlotManager()
    plots_dir = output_directory / "plots"
    plot_paths = {
        "training_curves": str(plots_dir / "training_curves.png"),
        "dataset_correlation": str(plots_dir / "dataset_correlation.png"),
        "neural_confusion_matrix": str(plots_dir / "neural_confusion_matrix.png"),
        "neuro_fuzzy_confusion_matrix": str(plots_dir / "neuro_fuzzy_confusion_matrix.png"),
    }

    val_loss = training_history.val_loss if any(not np.isnan(x) for x in training_history.val_loss) else None
    plot_manager.plot_training_curves(
        training_history.train_loss,
        val_loss=val_loss,
        title="Neural Network Training Curves",
        save_path=plot_paths["training_curves"],
        show=show_plots,
    )
    plot_manager.plot_correlation_heatmap(
        dataset,
        columns=[column for column in dataset.columns if dataset[column].dtype != object],
        title="Stress Dataset Correlation Heatmap",
        save_path=plot_paths["dataset_correlation"],
        show=show_plots,
    )
    plot_manager.plot_confusion_matrix_heatmap(
        neural_metrics["confusion_matrix"]["matrix"],
        labels=class_labels,
        title="Neural Network Confusion Matrix",
        save_path=plot_paths["neural_confusion_matrix"],
        show=show_plots,
    )
    plot_manager.plot_confusion_matrix_heatmap(
        neuro_fuzzy_metrics["confusion_matrix"]["matrix"],
        labels=class_labels,
        title="Neuro-Fuzzy Confusion Matrix",
        save_path=plot_paths["neuro_fuzzy_confusion_matrix"],
        show=show_plots,
    )
    return plot_paths


def save_metrics(output_directory: Path, metrics: Dict[str, Any]) -> Path:
    """Save full metrics payload to disk."""

    metrics_path = output_directory / "metrics.json"
    metrics_path.write_text(json.dumps(metrics, indent=4, default=_json_default), encoding="utf-8")
    return metrics_path


def _json_default(value: Any) -> Any:
    """Serialize NumPy and Path values to JSON-compatible objects."""

    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, (np.integer, np.floating)):
        return value.item()
    if isinstance(value, Path):
        return str(value)
    return value


def run_pipeline(config: SystemConfig, *, output_directory: Path, show_plots: bool = False) -> Dict[str, Any]:
    """Run the full training, evaluation, and persistence pipeline."""

    output_directory.mkdir(parents=True, exist_ok=True)
    logger = setup_logging(config)
    _ = logger

    tracker = ExperimentTracker(base_directory=output_directory / "experiments")
    persistence_manager = ModelPersistenceManager(base_directory=output_directory / "models")
    config_snapshot_path = output_directory / "config_snapshot.json"
    config.export_config(config_snapshot_path)

    experiment = tracker.start_experiment(
        f"{config.project_name} | v{config.project_version}",
        parameters=config.to_dict(),
        notes="Main training pipeline execution.",
    )
    LOGGER.info("Started experiment %s", experiment.experiment_id)

    try:
        dataset, dataset_path = generate_dataset(config)
        validation_report = DataValidator(strict=False).validate(dataset)
        if not validation_report.is_valid:
            LOGGER.warning("Dataset validation reported %d issues.", len(validation_report.issues))

        preprocessor = build_preprocessor(config)
        split_data = preprocessor.split_data(dataset)

        X_train = split_data.X_train
        X_val = split_data.X_val
        X_test = split_data.X_test
        y_train = split_data.y_train.to_numpy()
        y_val = split_data.y_val.to_numpy() if split_data.y_val is not None else None
        y_test = split_data.y_test.to_numpy()

        tracker.log_parameters(
            {
                "selected_features": preprocessor.get_selected_features(),
                "preprocessing_statistics": preprocessor.get_statistics(),
            }
        )

        neural_network = build_neural_network(config, input_size=X_train.shape[1])
        LOGGER.info("Training neural network with %d features.", X_train.shape[1])
        training_history = neural_network.fit(
            X_train.to_numpy(),
            y_train,
            X_val=X_val.to_numpy() if X_val is not None else None,
            y_val=y_val,
            verbose=True,
        )

        LOGGER.info("Training neuro-fuzzy system.")
        neuro_fuzzy_neural_network = build_neural_network(config, input_size=X_train.shape[1])
        neuro_fuzzy_system = build_neuro_fuzzy_system(neuro_fuzzy_neural_network, X_train, config)
        neuro_fuzzy_system.fit(
            X_train.to_numpy(),
            y_train,
            X_val=X_val.to_numpy() if X_val is not None else None,
            y_val=y_val,
            verbose=False,
        )

        neural_predictions = neural_network.predict(X_test.to_numpy())
        neuro_fuzzy_predictions = neuro_fuzzy_system.predict(X_test)

        neural_metrics = evaluate_predictions(y_test, neural_predictions, config.model.class_labels)
        neuro_fuzzy_metrics = evaluate_predictions(y_test, neuro_fuzzy_predictions, config.model.class_labels)

        plots = generate_plots(
            dataset=dataset,
            training_history=training_history,
            neural_metrics=neural_metrics,
            neuro_fuzzy_metrics=neuro_fuzzy_metrics,
            class_labels=config.model.class_labels,
            output_directory=output_directory,
            show_plots=show_plots,
        )

        experiment_metadata = {
            "experiment_id": experiment.experiment_id,
            "project_name": config.project_name,
            "project_version": config.project_version,
        }
        neural_model_metadata = persistence_manager.save_model(
            neural_network,
            model_name=f"{config.model.model_name}_neural",
            version=config.model.version,
            serialization_format="pickle",
            experiment_metadata=experiment_metadata,
        )
        neuro_fuzzy_model_metadata = persistence_manager.save_model(
            neuro_fuzzy_system,
            model_name=f"{config.model.model_name}_neuro_fuzzy",
            version=config.model.version,
            serialization_format="pickle",
            experiment_metadata=experiment_metadata,
        )

        tracker.track_model_version(config.model.version)
        tracker.log_artifact("dataset", dataset_path)
        tracker.log_artifact("config_snapshot", config_snapshot_path)
        tracker.log_artifact("neural_model", neural_model_metadata.artifact_path)
        tracker.log_artifact("neuro_fuzzy_model", neuro_fuzzy_model_metadata.artifact_path)
        for plot_name, plot_path in plots.items():
            tracker.log_artifact(plot_name, plot_path)

        summarized_results = {
            "neural_network": summarize_metrics(neural_metrics),
            "neuro_fuzzy_system": summarize_metrics(neuro_fuzzy_metrics),
        }
        tracker.log_metrics(
            {
                "neural_accuracy": summarized_results["neural_network"]["accuracy"],
                "neuro_fuzzy_accuracy": summarized_results["neuro_fuzzy_system"]["accuracy"],
                "neural_f1_macro": summarized_results["neural_network"]["f1_macro"],
                "neuro_fuzzy_f1_macro": summarized_results["neuro_fuzzy_system"]["f1_macro"],
            }
        )

        metrics_payload = {
            "experiment_id": experiment.experiment_id,
            "dataset_validation": validation_report.to_dict(),
            "preprocessing": preprocessor.get_statistics(),
            "training_history": asdict(training_history),
            "results": {
                "neural_network": neural_metrics,
                "neuro_fuzzy_system": neuro_fuzzy_metrics,
            },
            "artifacts": {
                "dataset_path": str(dataset_path),
                "plots": plots,
            },
        }
        metrics_path = save_metrics(output_directory, metrics_payload)
        tracker.log_artifact("metrics", metrics_path)

        tracker.end_experiment(
            status="completed",
            final_metrics={
                "neural_accuracy": summarized_results["neural_network"]["accuracy"],
                "neuro_fuzzy_accuracy": summarized_results["neuro_fuzzy_system"]["accuracy"],
            },
        )

        artifacts = PipelineArtifacts(
            dataset_path=str(dataset_path),
            neural_model_path=neural_model_metadata.artifact_path,
            neuro_fuzzy_model_path=neuro_fuzzy_model_metadata.artifact_path,
            neural_metadata_path=neural_model_metadata.metadata_path,
            neuro_fuzzy_metadata_path=neuro_fuzzy_model_metadata.metadata_path,
            experiment_record_path=str((output_directory / "experiments" / f"{experiment.experiment_id}.json")),
            metrics_path=str(metrics_path),
            config_snapshot_path=str(config_snapshot_path),
            plot_paths=plots,
        )

        return {
            "experiment_id": experiment.experiment_id,
            "metrics": summarized_results,
            "artifacts": asdict(artifacts),
        }
    except Exception:
        tracker.end_experiment(status="failed")
        LOGGER.exception("Pipeline execution failed.")
        raise


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments."""

    parser = argparse.ArgumentParser(description="Run the neuro-fuzzy stress detection training pipeline.")
    parser.add_argument("--config", type=Path, default=None, help="Optional path to a JSON config file.")
    parser.add_argument(
        "--data-path",
        type=Path,
        default=Path(DATA_PATH),
        help="CSV path used by the simplified step-by-step pipeline.",
    )
    parser.add_argument(
        "--basic-pipeline",
        action="store_true",
        help="Run the simplified step-by-step pipeline flow.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("artifacts/pipeline_runs"),
        help="Directory where models, metrics, plots, and logs will be stored.",
    )
    parser.add_argument(
        "--export-default-config",
        type=Path,
        default=None,
        help="Export the default config to the given path and exit.",
    )
    parser.add_argument(
        "--show-plots",
        action="store_true",
        help="Display generated plots interactively in addition to saving them.",
    )
    return parser.parse_args()


def main() -> int:
    """CLI entrypoint."""

    args = parse_args()

    if args.export_default_config is not None:
        export_default_config(args.export_default_config)
        print(json.dumps({"exported_config": str(args.export_default_config)}, indent=4))
        return 0

    if args.basic_pipeline:
        run_basic_pipeline(args.data_path)
        return 0

    config = load_system_config(args.config) if args.config is not None else load_system_config()
    results = run_pipeline(config, output_directory=args.output_dir, show_plots=args.show_plots)
    print(json.dumps(results, indent=4, default=_json_default))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
